### ISSUE TITLE
Bug - Crash when manually open `nanddump.bin`

### ISSUE THREAD

**Issue by Sopor** [Octal450/J-Runner-with-Extras#48]
**Describe the bug**
If i try to manually load my `nanddump.bin` (Console type: Trinity) J-Runner seems to randomly crash.

Sometimes it works, sometimes not.

If i select the console type and glitch before loading the `nanddump.bin` there is a higher success rate, but it can still crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click load source
2. Select `nanddump.bin` and open it.

**Expected behaviour**
Sometimes when i open `nanddump.bin` it do select console type and glitch by itself (that is the expected behaviour), but most of the times it crash instead.

**System (please complete the following information):**
 - OS: Windows 10 x64 22H2
 - Version: J-Runner 3.3.0 r2 (I don't know if you want my Windows version or J-Runner version here 🤔 )

**Additional context**
Here are two crash logs. They don't look the same, so i have included them both.

<details>
<summary>Error.log 1</summary>
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.get_SelectedItem()
   at System.Windows.Forms.ComboBox.get_Text()
   at System.Windows.Forms.Control.set_Text(String value)
   at System.Windows.Forms.ComboBox.set_Text(String value)
   at System.Windows.Forms.ComboBox.UpdateText()
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at JRunner.Panels.XeBuildPanel.setComboCB(Boolean erase, Boolean wait)
   at JRunner.Panels.XeBuildPanel.<txtMBname_TextChanged>b__112_1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
</details>

<details>
<summary>Error.log 2</summary>
System.ArgumentOutOfRangeException: InvalidArgument=Value of '0' is not valid for 'index'.
Parameter name: index
   at System.Windows.Forms.ComboBox.ObjectCollection.get_Item(Int32 index)
   at System.Windows.Forms.ComboBox.UpdateText()
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at JRunner.Panels.XeBuildPanel.setComboCB(Boolean erase, Boolean wait)
   at JRunner.Panels.XeBuildPanel.<txtMBname_TextChanged>b__112_1()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
</details>

**Comment by Octal450** [comment]
> (I don't know if you want my Windows version or J-Runner version here 🤔 )

Because I need to know what versions you're using to debug?

You have a corrupted dump, no such bug exists. However we probably should handle this gracefully rather than crashing. Please send me link to the nand dump.

Kind Regards,
Josh

**Comment by Sopor** [comment]
> > (I don't know if you want my Windows version or J-Runner version here 🤔 )
> 
> Because I need to know what versions you're using to debug?

When looking on other issues it seems that some writes the Windows version and some writes the J-Runner version. Maybe you should specify what version you want here instead of only write `Version` 😊

I have uploaded the nanddump.bin here: `https://gofile.io/d/FxSJ7b`

That file was extracted by a company. It was 10 years ago and the Xbox 360 is still working. Very strange that the nanddump.bin is corrupted. It was sent to me in a ZIP file, so the bin must have been corrupted before it was sent to me. If it was sent to me as a bin file it could have been corrupted on the way to me.

**Comment by Octal450** [comment]
I am completely sorry. I misread your message. I thought you were asking why I needed the info. I apologize. That’s a good note though, I will clarify. 

Thank you for the link. I will download it tonight and investigate as soon as I can. I am a little busy right now with college but I will check this out. 

Kind Regards,
Josh

**Comment by Sopor** [comment]
@Octal450 If you haven't downloaded the file yet, please do it soon because the link will soon die ...

It is possible to upload zip files on GitHub, but maybe you don't want them here for some reason? 🙂

**Comment by Octal450** [comment]
Sorry, I got busy with finals. Please upload.
Kind Regards,
josh

**Comment by Sopor** [comment]
[nanddump.zip](https://github.com/Octal450/J-Runner-with-Extras/files/13606827/nanddump.zip)
